### PR TITLE
chore: upgrade goverter to v1.3.0

### PR DESCRIPTION
**Pull request by pauhull**

### CODE REVIEW

**Comment by jmattheis** [comment]
This is actually related to the method below

https://github.com/hetznercloud/hcloud-go/blob/8e3bd45f94bf47da91b80b601a202814f4e93e84/hcloud/schema_gen.go#L241-L244

`schema.Error` doesn't have the field `response` therefore the ignore is a misconfiguration. Still the error references the wrong method but I'm not sure why yet.

**Comment by pauhull** [comment]
Oh, I didn't see that (and I assumed it was correct because it worked before). No, I copied the error messages directly from the console.

**Comment by jmattheis** [comment]
I get this error when executing goverter without any changes on this branch:
```
Error while creating converter method:
    func (github.com/hetznercloud/hcloud-go/v2/hcloud.converter).SchemaFromError(github.com/hetznercloud/hcloud-go/v2/hcloud.Error) github.com/hetznercloud/hcloud-go/v2/hcloud/schema.Error

| github.com/hetznercloud/hcloud-go/v2/hcloud.Error
|
source.
target.response
|      |
|      | ???
|
| github.com/hetznercloud/hcloud-go/v2/hcloud/schema.Error

Field "response" does not exist.
Remove or adjust field settings referencing this field.
```
Your first and second error are the same.

**Comment by jooola** [comment]
Probably related to https://github.com/hetznercloud/hcloud-go/commit/95582395dfb1039f4ce4f10a1ac9c068db93a867

**Comment by pauhull** [comment]
> I get this error when executing goverter without any changes on this branch:
> 
> ```
> Error while creating converter method:
>     func (github.com/hetznercloud/hcloud-go/v2/hcloud.converter).SchemaFromError(github.com/hetznercloud/hcloud-go/v2/hcloud.Error) github.com/hetznercloud/hcloud-go/v2/hcloud/schema.Error
> 
> | github.com/hetznercloud/hcloud-go/v2/hcloud.Error
> |
> source.
> target.response
> |      |
> |      | ???
> |
> | github.com/hetznercloud/hcloud-go/v2/hcloud/schema.Error
> 
> Field "response" does not exist.
> Remove or adjust field settings referencing this field.
> ```
> 
> Your first and second error are the same.

Sorry, that was my mistake. You're right, goverter works as intended here. But the error about ignoring non-existing fields is new, right? I checked with goverter v1.2.0 and the error wasn't there (which threw me off)

**Comment by pauhull** [comment]
> Probably related to [9558239](https://github.com/hetznercloud/hcloud-go/commit/95582395dfb1039f4ce4f10a1ac9c068db93a867) where we introduced the Error.response field.

I don't think so, 95582395dfb1039f4ce4f10a1ac9c068db93a867 was merged on Oct 20 and 6feda4d9b0e7cf3f5a17a4b38504abbe5213883d was merged on Dec 12

**Comment by jmattheis** [comment]
Yeah, with [v1.3.0](https://goverter.jmattheis.de/changelog#v1-3-0) goverter will error when not existing fields are configured in `:ignore` or `:map`.

**Review by jooola — APPROVED** [review]
:rocket:

**Pull request merged**
